const language = {
    ptbr: {
        menu: {
            "menu-subtitle": "Cientista da Computação",
            "menu-home": "Início",
            "menu-portfolio": "Portfólio"
        },
        home: {
            "content-name-allign": "Olá, meu nome é Marcelo",
            "welcome-1": "Sou Programador, Game Designer e Arquiteto de Software",
            "welcome-2": "Gosto de criar soluções computacionais incríveis, com um bom desempenho, elegantes visualmente e apaixonantes.",
            "welcome-3": "Como posso te ajudar hoje?",
            "topic-name-1": " Idiomas",
            "topic-name-2": " Objetivo",
            "topic-name-3": " Experiência profissional",
            "topic-name-4": " Formação acadêmica",
            "topic-name-5": " Programação",
            "topic-name-6": " Outros conhecimentos",
            "topic-name-7": " Hobbies",
            "topic-name-8": "  Glossário",
            "desc-obj": "Criar soluções computacionais incríveis, com um bom desempenho, elegantes visualmente e apaixonantes.",
            "verisoft-1": "• Desenvolvimento e manutenção de diversos aplicativos para Android, entre eles Claro Banca, Vivo Proteção Financeira, Bancah, Uol Leia+ Livros, Curso de Bolso.",
            "verisoft-2": "",
            "cit-1": "• Desenvolvimento de internet banking para dispositivos móveis utilizando o framework de desenvolvimento híbrido Kony, com JavaScript, para Android e iOS.",
            "cit-2": "• Desenvolvimento de aplicativo para gestão de cartão de credito para dispositivos móveis Android para uma das maiores empresas bancarias do Brasil.",
            "click-1": "•	Correção e atualização de diversas ferramentas existentes no portal.",
            "click-2": "•	Desenvolvimento integral de uma ferramenta para controle de exercícios educativos. Esta ferramenta possibilita um professor criar exercícios online para seus alunos. Entre suas funções ela gera instantaneamente a nota do aluno, relatorios(com filtros), cache de respostas dos alunos(não perde as informações mesmo em caso de conexão instável), controle de tempo respondendo e periodo limite para realizar os exercicios.",
            "click-3": "•	Entre os clientes, 'Centro Paula Souza', 'Prefeitura do Rio Grande do Norte'.",
            "click-4": "",
            "art-1": "•	Desenvolvimento de softwares de controle interno da empresa, principalmente referente a gestão de 'Fretes/transporte', além da criação de software para otimizar os setores internos em geral.",
            "art-2": "•	Criação de software para otimizar a comunicação do sistema de folha de pagamento 'TOTVS'.",
            "people-1": "•	Instrutor responsável por diversos cursos entre todas as faixas etárias.",
            "people-2": "",
            "brSim-1": "•	Desenvolvimento de softwares para simulação de aviões profissionais (FTD Fligth Training Device), criando comunicação entre hardware e software de simulação (Ms Flight Simulator). Ferramenta Borland Delphi junto da biblioteca gráfica OpenGL.",
            "brSim-2": "•	Entre os clientes, 'Companhia Aérea TAM', 'Escola de Aviação EDAPA', 'Escola de Aviação EJ', 'Aeroclube de Bragança'.",
            "language-port-1": "Português",
            "language-port-2": "Nativo",
            "language-eng-1": "Inglês",
            "language-eng-2": "Intermediário",
            "language-eng-3": "• Leitura: Avançado",
            "language-eng-4": "• Conversação : Intermediário",
            "ies2-1": "• Responsável por incluir processos de desenvolvimento dentro do time React Native, analisar e criar padrões de código/arquitetura, processos de build/entrega, testes, suporte aos desenvolvedores e tomadas de decisões técnicas de impacto dentro do projeto.",
            "ies2-2": "• Apresentei um planejamento de refatoração na parte mais sensível da aplicação, este planejamento foi executado trazendo uma melhora significativa na visão dos clientes ao produto.",
            "ies2-time": "09/2019 ~ Atualmente",
            "ies2-role": "Desenvolvedor React Native",
            "verisoft-time": "11/2017 ~ 09/2019",
            "verisoft-role": "Desenvolvedor Android",
            "cit-time": "08/2015 ~ 11/2017",
            "cit-role": "Desenvolvedor Mobile",
            "click-time": "05/2014 ~ 08/2015",
            "click-role": "Desenvolvedor Web",
            "art-time": "06/2012 ~ 06/2013",
            "art-role": "Analista de Sistemas",
            "people-time": "08/2009 ~ 03/2011",
            "people-role": "Instrutor Técnico",
            "brSim-time": "08/2007 ~ 08/2008",
            "brSim-role": "Programador",
            "other-gamedev": "Dev. jogos eletrônicos",
            "hobbies-music": "Música",
            "hobbies-travel": "Cinema",
            "hobbies-programming": "Programação",
            "hobbies-games": "	Jogos Eletrônicos",
            "glossary-course": "Conhecimento acadêmico e/ou cursos",
            "glossary-exp": "Experiência profissional",
            "glossary-personal": "Utiliza em projetos pessoais",
            "glossary-now": "Utilizando atualmente"
        },
        contact: {
            "contact-message-portifolio": "Hey, antes de ir embora, dê um pulinho no meu portfólio :)",
            "contact-message-profile": "Hey, antes de ir embora, dê um pulinho no meu perfil :)",
        },
        portfolio: {
            "play-online": "Jogar online",
            "sourcecode": "Código fonte",
            "tri-1": "Internet banking para dispositivos móveis utilizando o framework de desenvolvimento híbrido Kony, para Android e iOS.",
            "tri-2": "No app do Tribanco é possivel consultar o saldo e extrato de todas suas contas, o valor a ser repassado do Correspondente Tribanco e ainda tem na mão o histórico de transações e remuneração, em qualquer lugar, a qualquer hora! ",
            "tri-3": "Ano: 2016",
            "aulapp-1": "Aplicativo para ensino a distância com diversas ferramentas, entre elas criação de turmas, aulas ao vivo, fórum de discussão, exercícios on-line, consumo multimídia e etc.",
            "aulapp-2": "O aplicativo possui 2 frentes principais, um LMS para instituições de ensino e um marktplace para criadores de conteúdos venderem seus cursos.",
            "aulapp-3": "Ano: 2020",
            "gamification-1": "Trabalho de conclusão de curso para o bacharelado de ciência da computação.",
            "gamification-2": "É apresentado nesta monografia informações sobre o que é um sistema gamificado e como é possivel criar um.",
            "gamification-3": "Juntamente com a monografia foi desenvolvido um pequeno sistema gamificado para demostrar alguns conceitos apresentados na monografia",
            "gamification-4": "Ano: 2015",
            "omg-1": "Projeto desenvolvido durante o bacharelado de ciência da computação dentro da materia de desenvolvimento de jogos eletrônicos.",
            "omg-2": "Neste jogo o personagem deve proteger sua casa de ser destruida por monstros alem de se manter vivo dos ataques inferidos contra ele.",
            "omg-3": "",
            "omg-4": "Ano: 2015",
            "gludum-1": "Rede social voltada a desenvolvedores de jogos eletrônicos, podendo trocar experiências, criar um perfil público e divulgar os jogos criados.",
            "gludum-2": "Não foi utilizado nenhum sistema pré-pronto na sua criação, todo o projeto foi programado do zero.",
            "gludum-3": "",
            "gludum-4": "Ano: 2015",
            "click-1": "Ferramenta desenvolvida para criar exercícios, alocar usuarios para realizar os exercícios, corrigir as respostas, gerar gráficos.",
            "click-2": "",
            "click-3": "Ano: 2015",
            "space-1": "Jogo para Android, possui um nível alto de dificuldade, os efeitos sonoros dinamicos e pontuação online",
            "space-2": "",
            "space-3": "",
            "space-4": "Ano: 2014",
            "break-1": "Pequeno jogo ao estilo breakout.",
            "break-2": "Ano: 2013",
            "music-1": "Dentre outras músicas que compus, resolvi gravar algumas, sem nenhum compromisso. =] ",
            "m12-1": "Banda de rock alternativo que participei de 2010 até 2014.",
            "m12-2": "[Guitarra, Voz, Composições]",
            "m12-3": "Tambem aqui, audio em versão 8bits (convertido por mim)",
            "itaucard-1": "Aplicativo para gestão de cartão de crédito para dispositivos móveis Android",
            "itaucard-2": "Itaú é uma das maiores empresas bancarias do Brasil, aplicativo possui mais de dez milhões downloads.",
            "itaucard-3": "Ano: 2017",
            "rupert-1": "Jogo criado com intuito de testar conceitos estudados sobre desenvolvimento de jogos eletrônicos.",
            "rupert-2": "Foi realizado testes com usuários, documentação de game-design e código facilmente escalonável.",
            "rupert-3": "Ano: 2017",
            "ultraretrovirus-1": "Jogo criado em 48 para a global game jam 2018",
            "ultraretrovirus-2": "Jogador controla um vírus de computador e deve transmiti-lo a tantos programas quanto possível, evitando o software de firewall.",
            "ultraretrovirus-3": "Ano: 2018",
            "livroh-1": "Aplicativo para leitura de livros e escuta de audiolivros.",
            "livroh-2": "Possui um enorme acervo e parceria com grandes publicadores. Leitor dinâmico que organiza o texto na tela e possibilita a alteração de cores e tamanho de fonte.",
            "livroh-3": "Ano: 2019",
            "bancah-1": "Aplicativo para leitura jornais e revistas.",
            "bancah-2": "Possui um enorme acervo e parceria com grandes editoras.",
            "bancah-3": "Ano: 2019",
            "epicgolf2d-1": "Jogo de golf para Android/Ios, finalista do Big Festival 2018 na categoria 'Melhor Projeto de Jogo de Entretenimento' ",
            "epicgolf2d-2": "Após festival, jogo recebeu suporte da publicadora ZPlay(Pop Star, Bomber Friends, Absolute Drift, Super Stickman Golf)",
            "epicgolf2d-3": "Ano: 2019",
            "ourAdventureTime-1": "Jogo feito sobre demanda, onde o cliente gostaria de um jogo que fosse possivel pedir sua atual esposa em casamento. ",
            "ourAdventureTime-2": "Ano: 2018",
            "ourAdventureTime-3": "",
            "venusparticleeditor-1": "Editor de particulas para usar juntamente do framework Monogame",
            "venusparticleeditor-2": "Ano: 2019",
            "venusparticleeditor-3": "",
        }
    },
    en: {
        menu: {
            "menu-subtitle": "Computer scientist",
            "menu-home": "Home",
            "menu-portfolio": "Portfolio"
        },
        home: {
            "content-name-allign": "Hi, my name is Marcelo",
            "welcome-1": "I'm a Programmer, Game Designer and Software Architect",
            "welcome-2": "I like to create amazing computer solutions, well-performing, visually elegant and exciting computing solutions.",
            "welcome-3": "How can I help you today?",
            "topic-name-1": " Languages",
            "topic-name-2": " Objective",
            "topic-name-3": " Professional experience",
            "topic-name-4": " Academic education",
            "topic-name-5": " Programming Skills",
            "topic-name-6": " Other knowledges",
            "topic-name-7": " Hobbies",
            "topic-name-8": " Glossary",
            "desc-obj": "Create incredible computing solutions, with a good performance, visually elegant and passionate.",
            "verisoft-1": "",
            "verisoft-2": "",
            "cit-1": "",
            "cit-2": "",
            "click-1": "",
            "click-2": "",
            "click-3": "",
            "click-4": "",
            "art-1": "",
            "art-2": "",
            "people-1": "",
            "people-2": "",
            "brSim-1": "",
            "brSim-2": "",
            "language-port-1": "Portuguese",
            "language-port-2": "Native",
            "language-eng-1": "English",
            "language-eng-2": "Intermediary",
            "language-eng-3": "• Read: Advanced",
            "language-eng-4": "• Talk : Intermediary",
            "ies2-time": "09/2019 ~ Today",
            "ies2-role": "React Native/Android Developer",
            "verisoft-time": "11/2017 ~ 09/2019",
            "verisoft-role": "Android Developer",
            "cit-time": "08/2015 ~ 11/2017",
            "cit-role": "Mobile Developer",
            "click-time": "05/2014 ~ 08/2015",
            "click-role": "Web Developer",
            "art-time": "06/2012 ~ 06/2013",
            "art-role": "System analyst",
            "people-time": "08/2009 ~ 03/2011",
            "people-role": "Technical instructor",
            "brSim-time": "08/2007 ~ 08/2008",
            "brSim-role": "Developer/Programmer",
            "other-gamedev": "Game development",
            "hobbies-music": "Music",
            "hobbies-travel": "Movies",
            "hobbies-programming": "Programming",
            "hobbies-games": "Electronic games",
            "glossary-course": "Academic knowledge and/or courses",
            "glossary-exp": "Professional experience",
            "glossary-personal": "Use in personal projects",
            "glossary-now": "Currently using"
        },
        contact: {
            "contact-message-portifolio": "Hey, before you leave, give my portfolio a visit :)",
            "contact-message-profile": "Hey, before you leave, give my profile visit :)",
        },
        portfolio: {
            "play-online": "play online",
            "tri-1": "",
            "tri-2": "",
            "tri-3": "Year: 2016",
            "aulapp-1": "",
            "aulapp-2": "",
            "aulapp-3": "Year: 2020",
            "gamification-1": "",
            "gamification-2": "",
            "gamification-3": ".",
            "gamification-4": "Year: 2015",
            "omg-1": " ",
            "omg-2": " ",
            "omg-3": "",
            "omg-4": "Year: 2015",
            "gludum-1": " ",
            "gludum-2": " ",
            "gludum-3": " ",
            "gludum-4": "Year: 2015",
            "click-1": "  ",
            "click-2": "   ",
            "click-3": "Year: 2015",
            "space-1": "",
            "space-2": "",
            "space-3": "",
            "space-4": "Year: 2014",
            "break-2": "Year: 2013",
            "itaucard-1": "",
            "itaucard-2": "",
            "itaucard-3": "Year: 2017",
            "rupert-1": "",
            "rupert-2": "",
            "rupert-3": "Year: 2017",
            "ultraretrovirus-1": "",
            "ultraretrovirus-2": "",
            "ultraretrovirus-3": "Year: 2018",
            "livroh-1": "",
            "livroh-2": "",
            "livroh-3": "Ano: 2019",
            "bancah-1": "",
            "bancah-2": ".",
            "bancah-3": "Ano: 2019",
            "epicgolf2d-1": "' ",
            "epicgolf2d-2": "",
            "epicgolf2d-3": "Ano: 2019",
            "ourAdventureTime-1": "o. ",
            "ourAdventureTime-2": "Ano: 2018",
            "ourAdventureTime-3": "",
            "venusparticleeditor-1": "",
            "venusparticleeditor-2": "Ano: 2019",
            "venusparticleeditor-3": "",
        }
    }
};

window.activeLanguage = getLanguage();

function getLanguage() {
    let mLanguage = getCookie("language");
    let mActiveLanguage = language.ptbr;

    if (!mLanguage) {
        setCookie("language", 1, 99);
        mLanguage = 1;
    }

    if (mLanguage == 1) {
        mActiveLanguage = language.ptbr;
    } else if (mLanguage == 2) {
        mActiveLanguage = language.en;
    }

    return mActiveLanguage;
}

function setLanguage() {
    if (activeLanguage == language.ptbr) {
        setCookie("language", 2, 99);
    } else {
        setCookie("language", 1, 99);
    }

    location.reload();
}
