import { CodeIcon } from '@phosphor-icons/react/dist/csr/Code'
import { DatabaseIcon } from '@phosphor-icons/react/dist/csr/Database'
import { FileCodeIcon } from '@phosphor-icons/react/dist/csr/FileCode'
import { FileJsIcon } from '@phosphor-icons/react/dist/csr/FileJs'
import { FileSqlIcon } from '@phosphor-icons/react/dist/csr/FileSql'
import { FileTsIcon } from '@phosphor-icons/react/dist/csr/FileTs'
import { FireIcon } from '@phosphor-icons/react/dist/csr/Fire'
import { GameControllerIcon } from '@phosphor-icons/react/dist/csr/GameController'
import type { Icon } from '@phosphor-icons/react'
import {
  siAndroid,
  siApollographql,
  siCss,
  siDelphi,
  siDocker,
  siElectron,
  siFirebase,
  siGithubactions,
  siGraphql,
  siHtml5,
  siJest,
  siJquery,
  siJavascript,
  siMobx,
  siMonogame,
  siMysql,
  siNestjs,
  siNodedotjs,
  siOpengl,
  siPhp,
  siPostgresql,
  siPrisma,
  siReact,
  siRedux,
  siRedis,
  siSentry,
  siSqlite,
  siStorybook,
  siStyledcomponents,
  siSwagger,
  siTypeorm,
  siTypescript,
} from 'simple-icons'
import type { SimpleIcon } from 'simple-icons'
import type { TechnologyName } from './types'

type TechnologyDefinition = {
  iconColor?: string
  icon: Icon
  label: string
  logo?: SimpleIcon
}

export const TECHNOLOGY_NAMES = [
  'react',
  'react-native',
  'typescript',
  'javascript',
  'java',
  'php',
  'jest',
  'html-css',
  'sql',
  'sql-server',
  'unity',
  'monogame',
  'csharp',
  'delphi',
  'firebase',
  'node-js',
  'opengl',
  'postgresql',
  'redux',
  'sentry',
  'amplitude',
  'apollo-client',
  'express',
  'mobx',
  'nestjs',
  'prisma',
  'storybook',
  'typeorm',
  'graphql',
  'redis',
  'docker',
  'jspreport',
  'surveyjs',
  'swagger',
  'realm',
  'aws',
  'aws-cognito',
  'github-actions',
  'next-js',
  'electron',
  'android-sdk',
  'css',
  'html',
  'jquery',
  'kony',
  'mysql',
  'exoplayer',
  'sqlite',
  'react-hooks',
  'styled-components',
  'frontegg',
  'software-architecture',
  'agile-methodologies',
  'ci-cd',
] as const satisfies readonly TechnologyName[]

export const TECHNOLOGIES: Record<TechnologyName, TechnologyDefinition> = {
  react: { icon: CodeIcon, label: 'React', logo: siReact },
  'react-native': { icon: CodeIcon, label: 'React Native', logo: siReact },
  typescript: { icon: FileTsIcon, label: 'TypeScript', logo: siTypescript },
  javascript: { icon: FileJsIcon, label: 'JavaScript', logo: siJavascript },
  java: { icon: FileCodeIcon, iconColor: '#ED8B00', label: 'Java' },
  jest: { icon: CodeIcon, label: 'Jest', logo: siJest },
  php: { icon: FileCodeIcon, iconColor: '#8892BE', label: 'PHP', logo: siPhp },
  'html-css': { icon: FileCodeIcon, label: 'HTML / CSS', logo: siHtml5 },
  sql: { icon: FileSqlIcon, iconColor: '#4479A1', label: 'SQL' },
  'sql-server': { icon: DatabaseIcon, iconColor: '#CC2927', label: 'Microsoft SQL Server' },
  unity: { icon: GameControllerIcon, label: 'Unity' },
  monogame: { icon: GameControllerIcon, label: 'MonoGame', logo: siMonogame },
  csharp: { icon: FileCodeIcon, iconColor: '#512BD4', label: 'C#' },
  delphi: { icon: FileCodeIcon, label: 'Delphi', logo: siDelphi },
  firebase: { icon: FireIcon, label: 'Firebase', logo: siFirebase },
  'node-js': { icon: FileJsIcon, label: 'Node.js', logo: siNodedotjs },
  opengl: { icon: CodeIcon, label: 'OpenGL', logo: siOpengl },
  postgresql: { icon: DatabaseIcon, label: 'PostgreSQL', logo: siPostgresql },
  redux: { icon: CodeIcon, label: 'Redux.js', logo: siRedux },
  sentry: { icon: CodeIcon, label: 'Sentry', logo: siSentry },
  amplitude: { icon: CodeIcon, iconColor: '#6C5CE7', label: 'Amplitude' },
  'apollo-client': { icon: CodeIcon, label: 'Apollo Client', logo: siApollographql },
  express: { icon: FileJsIcon, label: 'Express.js' },
  mobx: { icon: CodeIcon, label: 'MobX', logo: siMobx },
  nestjs: { icon: FileJsIcon, label: 'NestJS', logo: siNestjs },
  prisma: { icon: DatabaseIcon, label: 'Prisma', logo: siPrisma },
  storybook: { icon: CodeIcon, label: 'Storybook', logo: siStorybook },
  typeorm: { icon: DatabaseIcon, label: 'TypeORM', logo: siTypeorm },
  graphql: { icon: CodeIcon, label: 'GraphQL', logo: siGraphql },
  redis: { icon: DatabaseIcon, label: 'Redis', logo: siRedis },
  docker: { icon: CodeIcon, label: 'Docker', logo: siDocker },
  jspreport: { icon: FileCodeIcon, label: 'jsreport' },
  surveyjs: { icon: CodeIcon, label: 'SurveyJS' },
  swagger: { icon: CodeIcon, label: 'Swagger API', logo: siSwagger },
  realm: { icon: DatabaseIcon, iconColor: '#39477F', label: 'Realm' },
  aws: { icon: CodeIcon, iconColor: '#FF9900', label: 'AWS' },
  'aws-cognito': { icon: CodeIcon, iconColor: '#DD344C', label: 'AWS Cognito' },
  'github-actions': { icon: CodeIcon, label: 'GitHub Actions', logo: siGithubactions },
  'next-js': { icon: FileJsIcon, label: 'Next.js' },
  electron: { icon: CodeIcon, label: 'Electron', logo: siElectron },
  'android-sdk': { icon: CodeIcon, label: 'Android SDK', logo: siAndroid },
  css: { icon: FileCodeIcon, label: 'CSS', logo: siCss },
  html: { icon: FileCodeIcon, label: 'HTML', logo: siHtml5 },
  jquery: { icon: FileJsIcon, label: 'jQuery', logo: siJquery },
  kony: { icon: CodeIcon, label: 'Kony' },
  mysql: { icon: DatabaseIcon, label: 'MySQL', logo: siMysql },
  exoplayer: { icon: CodeIcon, iconColor: '#3DDC84', label: 'ExoPlayer' },
  sqlite: { icon: DatabaseIcon, label: 'SQLite', logo: siSqlite },
  'react-hooks': { icon: CodeIcon, label: 'React Hooks', logo: siReact },
  'styled-components': { icon: CodeIcon, label: 'Styled Components', logo: siStyledcomponents },
  frontegg: { icon: CodeIcon, label: 'FrontEgg' },
  'software-architecture': { icon: CodeIcon, label: 'Software Architecture' },
  'agile-methodologies': { icon: CodeIcon, label: 'Agile Methodologies' },
  'ci-cd': { icon: CodeIcon, label: 'CI/CD' },
}
