import { CodeIcon } from '@phosphor-icons/react/dist/csr/Code'
import { DatabaseIcon } from '@phosphor-icons/react/dist/csr/Database'
import { FileJsIcon } from '@phosphor-icons/react/dist/csr/FileJs'
import { FileTsIcon } from '@phosphor-icons/react/dist/csr/FileTs'
import { FireIcon } from '@phosphor-icons/react/dist/csr/Fire'
import { GameControllerIcon } from '@phosphor-icons/react/dist/csr/GameController'
import { FileCodeIcon } from '@phosphor-icons/react/dist/csr/FileCode'
import { FileSqlIcon } from '@phosphor-icons/react/dist/csr/FileSql'
import type { Icon } from '@phosphor-icons/react'
import type { ProjectTechnologyName } from './types'

type ProjectTechnologyDefinition = {
  icon: Icon
  label: string
}

export const PROJECT_TECHNOLOGY_NAMES = [
  'react',
  'react-native',
  'typescript',
  'javascript',
  'java',
  'php',
  'jest',
  'html-css',
  'sql',
  'sql-server',
  'unity',
  'monogame',
  'csharp',
  'delphi',
  'firebase',
  'node-js',
  'opengl',
  'postgresql',
  'redux',
  'sentry',
  'amplitude',
  'apollo-client',
  'express',
  'mobx',
  'nestjs',
  'prisma',
  'storybook',
  'typeorm',
  'graphql',
  'redis',
  'docker',
  'jspreport',
  'surveyjs',
  'swagger',
  'realm',
  'aws-cognito',
  'github-actions',
  'next-js',
  'electron',
  'android-sdk',
  'css',
  'html',
  'jquery',
  'kony',
  'mysql',
  'exoplayer',
  'sqlite',
  'react-hooks',
  'styled-components',
  'frontegg',
] as const satisfies readonly ProjectTechnologyName[]

export const PROJECT_TECHNOLOGIES: Record<
  ProjectTechnologyName,
  ProjectTechnologyDefinition
> = {
  react: { icon: CodeIcon, label: 'React' },
  'react-native': { icon: CodeIcon, label: 'React Native' },
  typescript: { icon: FileTsIcon, label: 'TypeScript' },
  javascript: { icon: FileJsIcon, label: 'JavaScript' },
  java: { icon: FileCodeIcon, label: 'Java' },
  jest: { icon: CodeIcon, label: 'Jest' },
  php: { icon: FileCodeIcon, label: 'PHP' },
  'html-css': { icon: FileCodeIcon, label: 'HTML / CSS' },
  sql: { icon: FileSqlIcon, label: 'SQL' },
  'sql-server': { icon: DatabaseIcon, label: 'Microsoft SQL Server' },
  unity: { icon: GameControllerIcon, label: 'Unity' },
  monogame: { icon: GameControllerIcon, label: 'MonoGame' },
  csharp: { icon: FileCodeIcon, label: 'C#' },
  delphi: { icon: FileCodeIcon, label: 'Delphi' },
  firebase: { icon: FireIcon, label: 'Firebase' },
  'node-js': { icon: FileJsIcon, label: 'Node.js' },
  opengl: { icon: CodeIcon, label: 'OpenGL' },
  postgresql: { icon: DatabaseIcon, label: 'PostgreSQL' },
  redux: { icon: CodeIcon, label: 'Redux.js' },
  sentry: { icon: CodeIcon, label: 'Sentry' },
  amplitude: { icon: CodeIcon, label: 'Amplitude' },
  'apollo-client': { icon: CodeIcon, label: 'Apollo Client' },
  express: { icon: FileJsIcon, label: 'Express.js' },
  mobx: { icon: CodeIcon, label: 'MobX' },
  nestjs: { icon: FileJsIcon, label: 'NestJS' },
  prisma: { icon: DatabaseIcon, label: 'Prisma' },
  storybook: { icon: CodeIcon, label: 'Storybook' },
  typeorm: { icon: DatabaseIcon, label: 'TypeORM' },
  graphql: { icon: CodeIcon, label: 'GraphQL' },
  redis: { icon: DatabaseIcon, label: 'Redis' },
  docker: { icon: CodeIcon, label: 'Docker' },
  jspreport: { icon: FileCodeIcon, label: 'jsreport' },
  surveyjs: { icon: CodeIcon, label: 'SurveyJS' },
  swagger: { icon: CodeIcon, label: 'Swagger API' },
  realm: { icon: DatabaseIcon, label: 'Realm' },
  'aws-cognito': { icon: CodeIcon, label: 'AWS Cognito' },
  'github-actions': { icon: CodeIcon, label: 'GitHub Actions' },
  'next-js': { icon: FileJsIcon, label: 'Next.js' },
  electron: { icon: CodeIcon, label: 'Electron' },
  'android-sdk': { icon: CodeIcon, label: 'Android SDK' },
  css: { icon: FileCodeIcon, label: 'CSS' },
  html: { icon: FileCodeIcon, label: 'HTML' },
  jquery: { icon: FileJsIcon, label: 'jQuery' },
  kony: { icon: CodeIcon, label: 'Kony' },
  mysql: { icon: DatabaseIcon, label: 'MySQL' },
  exoplayer: { icon: CodeIcon, label: 'ExoPlayer' },
  sqlite: { icon: DatabaseIcon, label: 'SQLite' },
  'react-hooks': { icon: CodeIcon, label: 'React Hooks' },
  'styled-components': { icon: CodeIcon, label: 'Styled Components' },
  frontegg: { icon: CodeIcon, label: 'FrontEgg' },
}
